apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: itest-container
        image: eu.gcr.io/earnest-acre-297416/ui-test
        ports:
        - containerPort: 80
