apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  labels:
    app: rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api-container
          image: eu.gcr.io/earnest-acre-297416/rest-api
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: postgress-config
          env:
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgress-secret
                  key: POSTGRESS_PASSWORD
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRESS_PASSWORD)@postgres-service:$(POSTGRES_PORT)/$(POSTGRES_DB) 
            - name: FLASK_ENV
              value: development

